#!/usr/bin/env bash
# Write a Bash script that displays Best School 10 times.
# Requirements:
#    You must use the while loop (for and until are forbidden)


n=1

while [ $n -le 10 ]
do
	echo "Best School"
	n=$(( n+1 ))
done
