#!/usr/bin/env bash
# Write a Bash script that displays Best School 10 times.
# Requirements:
#    You must use the until loop (for and while are forbidden)


n=0

until [ $n == 10 ]
do
	echo "Best School"
	n=$(( n+1 ))
done
