#!/usr/bin/env bash
# A Bash script that displays Best School 10 times.

n=1

while [ $n -le 10 ]
do
	if [ $n == 9 ]
	then
		echo "Best School"
		echo "Hi"
		n=$(( n+1 ))
	else 
		echo "Best School"
                n=$(( n+1 ))
	fi
done
