#!/usr/bin/env bash
#Write a Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.
#Requirements:
#    You must use the while loop (for and until are forbidden)
#    You must use the if statement


n=1

while [ $n -le 10 ]
do
	if [ $n == 9 ]
	then
		echo "Best School"
		echo "Hi"
		n=$(( n+1 ))
	else 
		echo "Best School"
                n=$(( n+1 ))
	fi
done
