#!/usr/bin/env bash
# A Bash script that loops from 1 to 100, and: 
#    displays bad luck for the 4th loop iteration
#    displays good luck for the 8th loop iteration
#    displays Best School for the other iterations
# Requirements:
#    You must use the while loop (for and until are forbidden)
#    You must use the if, elif and else statements


n=1

while [ $n -le 10 ]
do
	if [ $n == 4 ]
	then
		echo "bad luck"
		n=$(( n+1 ))
	elif [ $n == 8 ]
	then
		echo "good luck"
		n=$(( n+1 ))
	else
		echo "Best School"
                n=$(( n+1 ))
	fi
done
