#!/usr/bin/env bash
# A Bash script that displays Best School 10 times.

n=1

while [ $n -le 10 ]
do
	if [ $n == 4 ]
	then
		echo "bad luck"
		n=$(( n+1 ))
	elif [ $n == 8 ]
	then
		echo "good luck"
		n=$(( n+1 ))
	else
		echo "Best School"
                n=$(( n+1 ))
	fi
done
