#!/usr/bin/env bash
# Write a Bash script that displays the time for 12 hours and 59 minutes:
#    display hours from 0 to 12
#    display minutes from 1 to 59
# Requirements:
#    You must use the while loop (for and until are forbidden)

h=0


while [ $h -le 12 ]
do
	echo "Hour: $h"
	m=1
	while [ $m -le 59 ]
	do
		echo "$m"
		m=$(( m+1 ))
	done
	h=$(( h+1 ))
done
